### ISSUE TITLE
Add support for post-render append/prepend

### ISSUE THREAD

**Issue by twigkit** [twigkit/tempo#10]

**Comment by dascgo** [comment]
this should be easy, have it working in my local tempo.js. In the render function:

change: utils.clearContainer(this.templates.container); to:

if(arguments.length === 1){
// if the old call, clear out the existing content
// otherwise we will be passing append or prepend, so 
// we probably want to keep our content there.
utils.clearContainer(this.templates.container);
}

then, in render, where you have: this.templates.container.appendChild(fragment);

make it: 

if(arguments.length === 2 && arguments[1] == "prepend"){
this.templates.container.insertBefore(fragment, this.templates.container.firstChild);
}else{
this.templates.container.appendChild(fragment);
}

this will allow content to be appended or prepended AND keep content that was already added (something I needed)

also, will not break old calls that just call render(data) that dont have another param. I just hacked this together, but will let you know if i run into problems

**Comment by mrolafsson** [comment]
great stuff! i'll incorporate this in the next release.

**Comment by mrolafsson** [comment]
Can you see if this fixes your issue? https://github.com/twigkit/tempo/raw/master/tempo.js

You can now do .append(data), .prepend(data) and .clear() where you would normally call render. These calls can be chained.

**Comment by twigkit** [comment]
Added in v1.3

**Comment by dascgo** [comment]
Sorry guys, I haven't had a chance to look at your update. At the time, I was trial testing tempo in a demo app and once that was done, I hadn't revisited it. However, loved tempo, and will definitely use it in my next R&D demo (or suggest it in a production app). When I can, I will use the updated version and get back to you if I run into any issues. Thanks for the great turn-around time on adding this functionality. :)
