### ISSUE TITLE
Setting values inside <li>

### ISSUE THREAD

**Issue by jamsi** [twigkit/tempo#25]
I've trawled through the docs but can't seem to find a solution;

To put it simply, I'm trying to use the following template.

```
<li data-template data-user-id="{{user_id}}">{{username}}</li>
```

My json object has "user_id", but I'm guessing I can only use {{user_id}} inside the li tags?

**Comment by twigkit** [comment]
Hi James, yes you're right, on the template node itself, we only do replacements in the 'id' and 'class' attributes. But I guess that's an over simplification. We simply didn't want to be too aggressive on those since the boundary was a bit blurred with nested templates (in which case, who overrides these first, the parent template or the child). Version 1.5 is well underway so if you have any suggestions on how you'd like this to work we'd be happy to fix promptly.

**Comment by twigkit** [comment]
Have you had any more thoughts on this?

**Comment by mrolafsson** [comment]
This is now supported in 2.0.
